### ISSUE TITLE
This is a risky way of loading images asynchronously 

### ISSUE THREAD

**Issue by ahmedk92** [mohabbatta/MaoTrailer#4]
https://github.com/mohabbatta/MaoTrailer/blob/cc8a20dbf2783e1a5f033f0ec581c5e245fc7a7e/MaoTrailer/extensions/image_extension.swift#L24

It doesn't support cancelation. For example, in a reusable collection/table view cells, a stale image loading request can successfully return and mistakenly override the current image.

**Comment by mohabbatta** [comment]
solved by using kingfisher
