### ISSUE TITLE
Consider overriding prepareForReuse and reset the imageView's image 

### ISSUE THREAD

**Issue by ahmedk92** [mohabbatta/MaoTrailer#5]
https://github.com/mohabbatta/MaoTrailer/blob/cc8a20dbf2783e1a5f033f0ec581c5e245fc7a7e/MaoTrailer/cells/PopularMoviesCollectionCell.swift#L14

This will avoid briefly showing the reused cell's image.

**Comment by mohabbatta** [comment]
Done ✅
